### PR TITLE
[WIP] Base classes for an upgrade decision engine

### PR DESCRIPTION
**Pull request by sc68cal**
An upgrade orchestrator will have a strategy for how an upgrade will be
done.

This is posted to GH to plant a flag in the ground and start discussion

### CODE REVIEW

**Comment by ikalnitsky** [comment]
Hmm.. It's a good idea to mention a need to live-migrate VMs, though I think it's better to postpone this for a while. Let's do first things first and design simple interface for now.

FWIW, so far we have the following requirements for the decision engine:

- Upgrade Driver as Param

  Upgrade Drivers is our interface to do an actual upgrade. Since the mission of decision engine is to emit a sequence of tasks for execution, we need to pass a driver to be used by those tasks.

- Top-Level Action to Trigger

  It seems like decision engine is our way to interact with upgrade procedure. Thus, such methods as `start_upgrade`, `pause_upgrade` and so on, provided by Sean in PR #52 should be moved out from upgrade driver into decision engine. An upgrade driver should provide a toolset for creating a task for a certain node (and/or service) but no more. It seems like it's what was originally intended and said in [Architecture doc](https://github.com/sc68cal/Kostyor/blob/master/doc/source/arch.rst#architecture).

I propose to start with that thoughts in mind and add strategies to live-migrate VMs in future patches. Who knows? Maybe later it'd look better to implement it other way.

Does it sound reasonable, guys? Or total bulshit? :)

**Comment by dstepanenko** [comment]
Sorry Ihor, this is total bullshit :(

Just kidding :+1: 

Talking about things like Live Migrations - I agree, let's postpone them for a while (we can simply add some draft but not dig too deep).

Talking about moving *_upgrade into decision engine, I think appropriate method of decision engine should simply fire the same method of UpgradeDriver. All this *_upgrade methods will be driver-specific, that is why this functionality should be bound to driver. In this case we should pass instance of UpgradeDriver to decision engine. As an alternative we can add property upgrade_driver to UpgradeTask, pass an instance of UpgradeTask as an argument to decision engine and instantiate instance of appropriate UpgradeDriver at the moment of task execution.

**Comment by sc68cal** [comment]
>It seems like decision engine is our way to interact with upgrade procedure. Thus, such methods as start_upgrade, pause_upgrade and so on, provided by Sean in PR #52 should be moved out from upgrade driver into decision engine. An upgrade driver should provide a toolset for creating a task for a certain node (and/or service) but no more. It seems like it's what was originally intended and said in Architecture doc.

Fair point. I think the goals of the decision engine is to do the following:

* Determine the order of the nodes to be upgraded
* Determine if a set of nodes need to be upgraded at the same time

For each node, in the order determined by the previous step:
* Do any `pre` or `post` tasks before a node is to be upgraded (like `host_evacuate_live` on the compute node to get all the instances migrated off)
* Call the upgrade driver to upgrade the node

So, we may need to move some methods around as we continue to discuss - but I think I agree with @dstepanenko that we can probably add `*_upgrade` methods to the decision engine and have them in both the decision engine and the driver for the time being.

**Comment by ikalnitsky** [comment]
@dstepanenko wrote:
> Talking about moving *_upgrade into decision engine, I think appropriate method of decision engine should simply fire the same method of UpgradeDriver

Em.. I'm not sure we need just *recalling* the method from driver, otherwise we will end up with decisions inside drivers with no reasons to have an independent decision engine to exist.

@dstepanenko wrote:
> As an alternative we can add property upgrade_driver to UpgradeTask, pass an instance of UpgradeTask as an argument to decision engine

That's actually, a good idea. 👍  At the first glance it looks very good, and may solve the problem of passing around different things. I mean, an UpgradeTask may become some sort of context info with info about driver, cluster and so on. 

@sc68cal wrote:
> Determine if a set of nodes need to be upgraded at the same time

I'm afraid we will end up with implementing one more orchestrator such as [Solar](https://github.com/openstack/solar), [Fuel](https://github.com/openstack/fuel-web) or [Mistral](https://github.com/openstack/mistral). Maybe think to reuse existing ones that allows to provide a graph of tasks?

Besides, I thought the idea was to do node-by-node upgrades, without parallel execution.

**Comment by sc68cal** [comment]
> I'm afraid we will end up with implementing one more orchestrator such as Solar, Fuel or Mistral. Maybe think to reuse existing ones that allows to provide a graph of tasks?

Yep, that's completely fine with me

**Comment by sc68cal** [comment]
> Besides, I thought the idea was to do node-by-node upgrades, without parallel execution.

Right. Ideally we can do a rolling upgrade and just go node by node, but there may be some instances where you need to upgrade a set of nodes at the same time. keystone , for example, is still working on supporting rolling upgrades and for a while you had to stop all the API servers, run the upgrade, and then bring them all back up.

**Comment by ikalnitsky** [comment]
> Right. Ideally we can do a rolling upgrade and just go node by node, but there may be some instances where you need to upgrade a set of nodes at the same time. keystone , for example, is still working on supporting rolling upgrades and for a while you had to stop all the API servers, run the upgrade, and then bring them all back up.

If we are going towards node-by-node upgrades, and parallel execution needs is only to workaround some things - I'm totally ok with it. :) Thanks for explanation. That's helpful.

**Comment by sc68cal** [comment]
> If we are going towards node-by-node upgrades, and parallel execution needs is only to workaround some things - I'm totally ok with it. :) Thanks for explanation. That's helpful.

Right. Ideally, all OpenStack services should be able to do rolling live upgrades - and any OpenStack service that doesn't, should be improved to do so. It's just that not everything is quite there yet, so we just need to be prepared for this contingency.

Happy to help :)

**Comment by dstepanenko** [comment]
> Em.. I'm not sure we need just recalling the method from driver, otherwise we will end up with decisions inside drivers with no reasons to have an independent decision engine to exist.

I think it won't be simply recalling in each of the cases. Especially, in complicated cases like upgrade cancelation and rolling back

**Comment by sc68cal** [comment]
This PR got a little messy. I'm going to create a new PR for *just the upgrade driver* piece.

**Pull request closed without merging**
