### PR TITLE
Add new commands. Small improvements of CLI.

### PR DESCRIPTION
**Pull request by jvarlamova**

### CODE REVIEW

**Comment by sc68cal** [comment]
This needs unit tests. There is some being worked on in #12 but this can't get merged until that PR merges and this branch is updated to have test coverage.

**Comment by sc68cal** [comment]
We'll re-open when this is able to be merged

**Comment by sc68cal** [comment]
@jvarlamova ok - I merged #12 - so you may have to rebase and solve any merge conflicts. Talk to you Tuesday

**Comment by sc68cal** [comment]
4bacade is a little vague on what exactly you fixed

**Comment by sc68cal** [comment]
the `tox.ini` file needs to be updated to actually run tests in the ` kostyor/cli/tests/unit/` directory

**Comment by sc68cal** [comment]
Sorry, not `tox.ini` - `.testr.conf`

**Comment by sc68cal** [comment]
You also committed some `.pyc` files. Those should not be committed.

**Comment by sc68cal** [comment]
I pushed some changes to enable Travis CI to run the unit tests for the CLI. This will need a rebase

**Comment by jvarlamova** [comment]
Ok, thanks, I'll fix it.

**Comment by sc68cal** [comment]
@jvarlamova we can handle the `conf.ini` issue in a separate review. Good work

**Pull request merged**
